//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par ManageDsk.rc
//
#define IDC_ACCEPT                      3
#define IDD_MANAGEDSK_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_INFOFICHIER                 129
#define IDB_EN                          130
#define IDB_FR                          131
#define IDD_IMPORT_FICHIER              132
#define IDB_SP                          132
#define IDD_EDIT_SECTEURS               133
#define IDD_EDIT_FICHIER                134
#define IDD_DIALCOMM                    135
#define IDD_DIALPARAMCOM                136
#define IDD_CHOIXCOULEUR                138
#define IDD_INFO_FLOPPY                 139
#define IDD_OUINON                      141
#define IDD_LISTEDIR                    142
#define IDD_INPUT_TRACKS                143
#define IDC_LIST                        1000
#define IDC_LIST1                       1000
#define IDC_EXPORT                      1001
#define IDC_LIST2                       1003
#define IDC_RENOMME                     1004
#define IDC_VALIDER                     1005
#define IDC_EXPORT2                     1006
#define IDC_SUPPRIMER                   1007
#define IDC_RENOMME2                    1008
#define IDC_SUPPRIME                    1009
#define IDC_NOM_FICHIER                 1010
#define IDC_SUPPRIME2                   1011
#define IDC_EDIT_SECTEURS               1012
#define IDC_TYPE                        1013
#define IDC_EDIT_FIC                    1014
#define IDC_LIRE                        1015
#define IDC_ADRESSE_DEB                 1016
#define IDC_LIRE2                       1017
#define IDC_SAUVE                       1018
#define IDC_ADRESSE_DEB2                1019
#define IDC_SAUVE3                      1020
#define IDC_LONGUEUR                    1021
#define IDC_EDIT_SECTEURS2              1022
#define IDC_SAUVE_DIRECT                1023
#define IDC_AJOUTEFIC                   1024
#define IDC_LONGUEUR2                   1025
#define IDC_AJOUTEFIC2                  1026
#define IDC_POINT_ENTREE                1027
#define IDC_SAUVE_DIRECT2               1028
#define IDC_SAUVE2                      1029
#define IDC_EDIT_FIC2                   1030
#define IDC_NOMDSK                      1031
#define IDC_POINT_ENTREE2               1032
#define IDC_NOMDSK2                     1033
#define IDC_USER                        1034
#define IDC_NOMDSK3                     1034
#define IDC_CREER                       1035
#define IDC_NETTOIE                     1036
#define IDC_BP_FR                       1037
#define IDC_BP_EN                       1038
#define IDC_CONTENU_DSK                 1039
#define IDC_KO_UTIL                     1040
#define IDC_BP_EN2                      1040
#define IDC_BP_UNKNOW                   1040
#define IDC_BP_SP                       1040
#define IDC_CREER2                      1041
#define IDC_TXT_NOMFIC                  1042
#define IDC_TEST                        1043
#define IDC_WRITE_FLOPPY                1043
#define IDC_TXT_USER                    1044
#define IDC_READ_FLOPPY                 1044
#define IDC_CONFIG                      1045
#define IDC_WRITE_FLOPPY2               1045
#define IDC_TXT_TYPE                    1046
#define IDC_READ_FLOPPY2                1046
#define IDC_TEST2                       1047
#define IDC_FORMAT_FLOPPY               1047
#define IDC_TXT_ADRDEB                  1048
#define IDC_FORMAT_FLOPPY2              1048
#define IDC_CONFIG2                     1049
#define IDC_TXT_LONGUEUR                1050
#define IDC_TXT_POINTENTREE             1051
#define IDC_CONTENU_DSK2                1052
#define IDC_STATIC_MODE_AJ              1053
#define IDC_RADIO_FORCE_BIN             1054
#define IDC_RADIO_FORCE_ASCII           1055
#define IDC_RADIO_CHOIX                 1056
#define IDC_TYPE_BIN                    1057
#define IDC_STATIC_MODE_AJ2             1058
#define IDC_TYPE_ASCII                  1059
#define IDC_RADIO_FORCE_BIN2            1060
#define IDC_STATIC_MODE_EXP             1061
#define IDC_STATIC_INFOFIC              1062
#define IDC_RADIO_FORCE_ASCII2          1063
#define IDC_RADIO_EXP_BIN               1064
#define IDC_STATIC_TYPEFIC              1065
#define IDC_RADIO_CHOIX2                1066
#define IDC_RADIO_EXP_ASCII             1067
#define IDC_ISAMSDOS                    1068
#define IDC_STATIC_MODE_EXP2            1069
#define IDC_READOLNY                    1070
#define IDC_RADIO_EXP_BIN2              1071
#define IDC_HIDE                        1072
#define IDC_RADIO_EXP_ASCII2            1073
#define IDC_VIEW_SECT                   1074
#define IDC_VIEW_ASCII                  1075
#define IDC_TRACK_STATIC                1076
#define IDC_SECT_STATIC                 1077
#define IDC_TRACK                       1078
#define IDC_SPIN_TRACK                  1079
#define IDC_VIEW_HEX                    1080
#define IDC_SECT                        1081
#define IDC_SCROLL                      1082
#define IDC_SPIN_SECT                   1083
#define IDC_STATIC_START                1084
#define IDC_STATIC_END                  1085
#define IDC_SCROLLSCR                   1086
#define IDC_LIST_BASIC                  1087
#define IDC_HEXA                        1088
#define IDC_BASIC                       1089
#define IDC_ECR                         1090
#define IDC_CRLF                        1091
#define IDC_CLEAR                       1092
#define IDC_SPIN_COL                    1093
#define IDC_STATIC_NBCOL                1094
#define IDC_STATIC_OFFSET               1095
#define IDC_STATIC_NBLIGNES             1096
#define IDC_SPIN_LIGNES                 1097
#define IDC_MODE0                       1098
#define IDC_MODE1                       1099
#define IDC_MODE2                       1100
#define IDC_SAVE                        1101
#define IDC_LISTE                       1102
#define IDC_DAMS                        1103
#define IDC_STATIC_VITESSE              1104
#define IDC_DESASS                      1105
#define IDC_COMBO_VITESSE               1106
#define IDC_STATIC_PARITE               1107
#define IDC_MAXPISTES                   1108
#define IDC_COMBO_PARITE                1109
#define IDC_DBL_WINDOW                  1110
#define IDC_BP_SEND                     1111
#define IDC_BP_SWAP                     1112
#define IDC_PROGRESS                    1113
#define IDC_BP_SEND2                    1113
#define IDC_INFORMATIONS                1114
#define IDC_BP_COMPARE                  1114
#define IDC_INFO_DISQUETTE              1115
#define IDC_STATIC_TXTCOL               1116
#define IDC_FACE0                       1117
#define IDC_FACE1                       1118
#define IDC_DOUBLESTEP                  1119
#define IDC_MSG_CONFIRMATION            1120
#define IDC_OUI                         1121
#define IDC_NON                         1122
#define IDC_OUITOUT                     1123
#define IDC_MFM                         1124
#define IDC_DETECT_MEDIA                1125
#define IDC_VITESSE1                    1126
#define IDC_STOP_ERROR                  1126
#define IDC_VITESSE2                    1127
#define IDC_DETAIL                      1127
#define IDC_CHANGE_RATE                 1128
#define IDC_DRIVEA                      1129
#define IDC_DRIVEB                      1130
#define IDC_CONFDRIVE                   1131
#define IDC_AVANCEE                     1132
#define IDC_VISU_DIR                    1133
#define IDC_VISU_DIR2                   1134
#define IDC_NBTRACKS                    1136
#define IDC_NB_TRACKS                   1137
#define IDC_BP_START_ASM                1138
#define IDC_NB_SECTS                    1139
#define IDC_EDIT1                       1140
#define IDC_START_ASM                   1141
#define IDC_RADIO1                      1141
#define IDC_RADIO_EXP_AUTO              1141
#define IDC_NBSECTS                     1142
#define IDC_RADIO_EXP_AUTO2             1142
#define IDC_CHECK1                      1143
#define IDC_KILL                        1144
#define IDC_COL00                       9200
#define IDC_COL01                       9201
#define IDC_COL02                       9202
#define IDC_COL03                       9203
#define IDC_COL04                       9204
#define IDC_COL05                       9205
#define IDC_COL06                       9206
#define IDC_COL07                       9207
#define IDC_COL08                       9208
#define IDC_COL09                       9209
#define IDC_COL10                       9210
#define IDC_COL11                       9211
#define IDC_COL12                       9212
#define IDC_COL13                       9213
#define IDC_COL14                       9214
#define IDC_COL15                       9215
#define IDC_COL16                       9216
#define IDC_COL17                       9217
#define IDC_COL18                       9218
#define IDC_COL19                       9219
#define IDC_COL20                       9220
#define IDC_COL21                       9221
#define IDC_COL22                       9222
#define IDC_COL23                       9223
#define IDC_COL24                       9224
#define IDC_COL25                       9225
#define IDC_COL26                       9226
#define IDC_COLCHOIX                    9230
#define IDC_NUMCOL                      9231

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
